FROM rabbitmq:3.10-management-alpine

ADD --chown=rabbitmq ./definitions.json /etc/rabbitmq/

ENV RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
ENV RABBITMQ_DEFAULT_PASS=root \
    RABBITMQ_DEFAULT_USER=root 