version: "3.8"
services:
  api:
    build: 
      context: src/UrlShortener.Api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
